inherit_from:
  - .rubocop_todo.yml

AllCops:
  Exclude:
    - "bin/**/*"
    - "db/migrate/**/*"
    - "db/schema.rb"
    - "config/**/*"
    - "script/**/*"

Rails:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes

Metrics/ModuleLength:
  Max: 100
  Exclude:
    - "spec/**/*"

Metrics/ClassLength:
  Max: 150

Metrics/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 10

Metrics/AbcSize:
  Max: 25
  Exclude:

Style/Documentation:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundMethodBody:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/BlockComments:
  Enabled: false

Layout/AlignHash:
  Enabled: false

Layout/IndentHash:
  Enabled: false

Layout/IndentArray:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Layout/ClosingParenthesisIndentation:
  Enabled: false

Layout/AlignArray:
  Enabled: false

Style/AndOr:
  Enabled: false

Layout/AlignParameters:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Style/WordArray:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/IfInsideElse:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 17

Metrics/PerceivedComplexity:
  Max: 17

Rails/HasAndBelongsToMany:
  Exclude:

Rails/Output:
  Exclude:
    - "db/seeds.rb"

Style/RedundantSelf:
  Enabled: false

Style/PercentLiteralDelimiters:
  Exclude:

Style/RegexpLiteral:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false
